# Generated by Django 5.1.15 on 2026-09-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the doctor was assigned to the patient.')),
                ('notes', models.TextField(blank=True, default='', help_text='Consultation notes, assignment reason, or medical remarks.')),
                ('doctor', models.ForeignKey(help_text='The doctor assigned to the patient.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor')),
                ('patient', models.ForeignKey(help_text='The patient who is assigned to the doctor.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'db_table': 'healthcare_patient_doctor_mappings',
                'ordering': ['-assigned_date'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'doctor'), name='unique_patient_doctor_mapping')],
            },
        ),
    ]
