# Generated by Django 5.1.15 on 2026-09-29 07:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal name of the patient.', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD).', null=True)),
                ('age', models.PositiveIntegerField(help_text='Age of the patient in years.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', help_text='Gender of the patient.', max_length=10)),
                ('contact_number', models.CharField(help_text='Contact phone number.', max_length=25)),
                ('email', models.EmailField(blank=True, default='', help_text='Optional email address of the patient.', max_length=254)),
                ('address', models.TextField(blank=True, default='', help_text='Residential address.')),
                ('medical_history', models.TextField(blank=True, default='', help_text='Brief medical history or existing conditions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The authenticated user who registered this patient record.', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'healthcare_patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
