# Generated by Django 5.1.15 on 2026-09-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name and title of the doctor (e.g., Dr. Jane Smith).', max_length=255)),
                ('specialization', models.CharField(help_text='Medical specialty (e.g., Cardiology, Dermatology, Pediatrics).', max_length=150)),
                ('license_number', models.CharField(db_index=True, help_text='Unique medical license registration number.', max_length=100, unique=True)),
                ('contact_number', models.CharField(help_text='Direct contact phone number.', max_length=25)),
                ('email', models.EmailField(help_text='Official contact email address.', max_length=254, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Total years of clinical medical experience.')),
                ('hospital_affiliation', models.CharField(blank=True, default='', help_text='Hospital, clinic, or medical center affiliation.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'healthcare_doctors',
                'ordering': ['name'],
            },
        ),
    ]
